name: Deploy Laravel Application

on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # or the version your Laravel app requires
          extensions: mbstring, intl, bcmath, gd, xml, ctype, json, mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-dev --optimize-autoloader

      - name: Generate application key
        run: php artisan key:generate --force
        env:
          APP_ENV: production

      - name: Run migrations
        run: php artisan migrate --force
        env:
          APP_ENV: production
          DB_CONNECTION: mysql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Deploy application
        run: |
          rsync -avz --exclude 'vendor' --exclude '.env' --exclude '.git' ./ user@server:/path/to/your/application
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}

      - name: Restart server (Optional)
        run: ssh user@server "sudo systemctl restart apache2" # Or nginx
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
